import java.util.*;

class Solution {
    public int[] sortItems(int n, int m, int[] group, List<List<Integer>> beforeItems) {

            for (int i = 0; i < n; i++) {
                        if (group[i] == -1)
                                        group[i] = m++;
                                                }

                                                        List<List<Integer>> itemGraph = new ArrayList<>();
                                                                List<List<Integer>> groupGraph = new ArrayList<>();

                                                                        for (int i = 0; i < n; i++)
                                                                                    itemGraph.add(new ArrayList<>());

                                                                                            for (int i = 0; i < m; i++)
                                                                                                        groupGraph.add(new ArrayList<>());

                                                                                                                int[] itemIn = new int[n];
                                                                                                                        int[] groupIn = new int[m];

                                                                                                                                for (int i = 0; i < n; i++) {
                                                                                                                                            for (int b : beforeItems.get(i)) {

                                                                                                                                                            itemGraph.get(b).add(i);
                                                                                                                                                                            itemIn[i]++;

                                                                                                                                                                                            if (group[i] != group[b]) {
                                                                                                                                                                                                                groupGraph.get(group[b]).add(group[i]);
                                                                                                                                                                                                                                    groupIn[group[i]]++;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                List<Integer> itemOrder = topo(itemGraph, itemIn, n);
                                                                                                                                                                                                                                                                                        List<Integer> groupOrder = topo(groupGraph, groupIn, m);

                                                                                                                                                                                                                                                                                                if (itemOrder.size() == 0 || groupOrder.size() == 0)
                                                                                                                                                                                                                                                                                                            return new int[0];

                                                                                                                                                                                                                                                                                                                    Map<Integer, List<Integer>> map = new HashMap<>();

                                                                                                                                                                                                                                                                                                                            for (int item : itemOrder) {
                                                                                                                                                                                                                                                                                                                                        map.putIfAbsent(group[item], new ArrayList<>());
                                                                                                                                                                                                                                                                                                                                                    map.get(group[item]).add(item);
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                    List<Integer> ans = new ArrayList<>();

                                                                                                                                                                                                                                                                                                                                                                            for (int g : groupOrder) {
                                                                                                                                                                                                                                                                                                                                                                                        ans.addAll(map.getOrDefault(g, new ArrayList<>()));
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                        return ans.stream().mapToInt(i -> i).toArray();
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                List<Integer> topo(List<List<Integer>> g, int[] in, int n) {
                                                                                                                                                                                                                                                                                                                                                                                                                        Queue<Integer> q = new LinkedList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                List<Integer> res = new ArrayList<>();

                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (in[i] == 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    q.offer(i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while (!q.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int x = q.poll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.add(x);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int y : g.get(x)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (--in[y] == 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            q.offer(y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.size() == n ? res : new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }